[package]
name = "grope"
version = "0.1.1"
authors = ["Alison Sanderson"]
edition = "2018"

[dependencies]
cairo-rs = {version = "0.5", features = ["png"]}
gdk = "0.9"
gdk-pixbuf = "0.5"
glib = "0.6"
gtk = "0.5"
gtk-sys = "0.7"
libc = "0.2"
memmap = "0.7"
